### ISSUE TITLE
Binaries are compiled against java 8

### ISSUE THREAD

**Issue by beornharris** [brendanSapience/UC4-Automic-AE-CLI-Binary-Repository#52]
Project documentation states that minimum requirement is Java 7, but execution fails with the following

```
$ java -version
java version "1.7.0_79"
Java(TM) SE Runtime Environment (build 1.7.0_79-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.79-b02, mixed mode)
$ java -jar OBJECTS_Export.jar -name "MOVE_FILES.JOBS" -m_export -e_dep_level 0 -commit -e_pck_path "$HOME/uc4_export"
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/uc4/api/InvalidUC4NameException : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at com.automic.specifics.ProcessSpecificCLI.processSpecificParameters(ProcessSpecificCLI.java:123)
        at com.automic.specifics.ProcessSpecificCLI.<init>(ProcessSpecificCLI.java:28)
        at com.automic.specifics.GoRunCommand.main(GoRunCommand.java:70)

```

According to [Java Wikipedia Article](https://en.wikipedia.org/wiki/Java_class_file) version 52 is Java 8.

I am not able to install/use java 8 on the target system.

**Comment by brendanSapience** [comment]
Hi,

I no longer work at CA and cannot maintain the repository. Can you send me an email with those details at brendan.sapience@gmail.com? i will make sure it gets to the right person for help.
